spring.application.name=inventory
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://juno-db:3306/inventoryDB?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}